JuliaLang/julialang.github.com

- _includes/links.html
Closes #112.
@simonbyrne's suggestion of removing the rss link provides just enough space so that "packages" can be squeezed in.
'Learning', 'teaching' and 'publications' could probably be consolidated in a future change.
> Add packages link, remove rss link

- downloads/index.md
Juliabox, S3, and status.julialang.org URLs all support HTTPS; use these as the default links.
> Use HTTPS URL for sites that support it

- LICENSE.md
This might create issues, but this will open source the contents of the website. 
Discuss below.
> adding license

- community/index.md
I also changed `ÌRC` to the more general `Chat Rooms` in order to enable other local communities with different languages to stay in touch and register their resources here.
* [julialang-es](https://gitter.im/Ismael-VC/julialang-es): Gitter chat room in Spanish.
> Add the julialang-es Spanish chat room at Gitter.

- downloads/index.md
cc @staticfloat release full-source-dist tarball is up now, for updating the checksums
> Update download links for v0.3.9

- _includes/juliacon-player.md
- _layouts/common.html
- index.md
This creates a mixin that can be used to include a random video from the JuliaCon 2015 playlist on Youtube. It's usage is exemplified by the changes to `index.md`.
> Create mixin for videos from JuliaCon (closes #257)

- downloads/index.md
We've done a pretty nice job of making the download page sell some of our strong integrations like Juno, JuliaBox, etc... do we want to make a Juno bundle for 0.4-rc1?  Do we want to ensure that JuliaBox is up and running with 0.4-rc1 before announcing further?
Pinging @one-more-minute @ViralBShah directly for these points.
> [WIP] Prepare v0.4.0-rc1 download linkage

- blog/_posts/2014-08-09-juliacon-opening-session.md
- blog/_posts/2014-08-09-juliacon-opt-session.md
Fixes rendering issues due to `<br\>` in http://julialang.org/blog/2014/08/juliacon-opt-session/ and http://julialang.org/blog/2014/08/juliacon-opening-session/. Also centers the videos.
> Fix br tags in juliacon 2014 blog posts

- blog/_posts/2015-10-23-auto-diff-in-julia.md
There were several glaring formatting issues with the old post as a result of me previewing the document in GitHub's markdown renderer rather than Jekyll's. I made these formatting corrections in this PR by previewing the post through a local Jekyll instance.
cc @ViralBShah
> Rework ForwardDiff blog post to resolve formatting issues

- downloads/index.md
- downloads/oldreleases.md
This is missing the gpg signatures which only @staticfloat can currently create with the existing key.
> Update download links for 0.3.12 and 0.4.1

- downloads/oldreleases.md
This bumps Juno to the latest Julia bugfix release. Unfortunately, these builds aren't signed yet – I'm not sure whether an unsigned newer release is better than a signed older one. We should be able to fix that within the next couple days, though.
> bump juno version

- index.md
The assertion that we use a "reasonable idiom in each language" is too easily argued against. I believe that phrase doesn't help sell the benchmarks. If you believe that, I think this change helps to provide one less avenue for attack.
> Don't claim benchmarks are idiomatic

- blog/_posts/2016-02-01-iteration.md
Summarizes the work of @mbauman, @Jutho, and myself on indexing and iteration, in an attempt to make this information more widespread.
Is there an easy way to preview it? I checked it using a locally-installed markdown renderer, and it looked fine, but that doesn't use all the nice highlighting.
> Add blog post on multidimensional iteration and indexing

- _includes/logo.svg
- Blue, red, and purple dots now have same y position
- Make red and purple dots have the same distance from the center of the green dot
> Fix logo dot alignment

- downloads/index.md
I'm still working on the bundles – they're not quite done yet, although since the bundle requires packages to be installed manually anyway, the non-bundled version isn't much more difficult.
Either way, we're well past the point where we just need to purge the LT stuff from existence, hence this change.
> Update juno download instructions

- community/index.md
This can prevent newcomers who want to follow the development
from wondering why the julia-dev traffic is so low. People
have mentioned in the past that they didn't discover immediately
that they had to subscribe to GitHub notifications.
> Mention that most development discussions happen on GitHub

- downloads/index.md
Remove PPA because it is not currently being maintained, move Fedora links to below the generic Linux binaries.
> Update links for 0.4.5

- community/index.md
We finished the homepage of Chinese community, and the julia.org.cn is for disccusions, which is included in the [homepage](http://julialang.cn)  :-)
The homepage is in the [repo](https://github.com/JuliaCN/juliacn.github.io)
> update link of JuliaCN

- blog/_posts/2016-03-27-arrays-iteration.md
As described [here](https://groups.google.com/d/msg/julia-dev/mKoVG54jygM/fnnwgn8nAAAJ), this is introductory material describing some challenges for supporting certain array types and operations. It will be paired with a shortly-to-be-filed GitHub issue outlining possible solutions.
If upon review you find this unsatisfying as a blog post, or find the split between problem & solution awkward, please recommend a better forum.
> Add blog post on challenging AbstractArray types

- community/index.md
We're just establishing a regular user group in Berlin.
CC @daveh19
> community: add link to Berlin group

- downloads/index.md
If anyone wants to verify these downloads, would be appreciated.
> Update download links from 0.4.5 to 0.4.6

- teaching/index.md
This adds the MATH3076/3976 course at U. Sydney.
I used "Fall 2016", which in this case means "Southern Hemisphere Fall 2016".
> Added U. Sydney course

- community/index.md
Part of #383. I think that issue should be left open as a reminder in case the new organizations get used.
Also fixes an en dash in BioJulia.
> Add JuliaIO organization

- downloads/index.md
Plots.jl is in the top 20 packages [according to the Julia Pulse (ranking via stars)](http://pkg.julialang.org/pulse.html). Because of its user-friendliness and high amount of development activity (with help always available in the Gitter channel), I believe it should be right here, front and center, on the Julia webiste. On the otherhand, most people will not be plotting directly into Compose.jl, and so I believe showing that as a "plotting package" confuses most newcommers (as evidenced by the questions we get in the Gitter/IRC about it. Plus the link was broken).
So I added a part for Plots.jl and removed the Part about Compose.jl. I think Plots.jl should come by default on JuliaBox to match this as well.
> Change Plot recommendations

- downloads/index.md
I used the 0.4-rc version of this file as a template and I took the download links from https://groups.google.com/forum/#!topic/julia-users/shrnNHpyliA.
Fixes https://github.com/JuliaLang/julia/issues/17881
> Link to the 0.5 release candidate downloads

- downloads/index.md
- downloads/oldreleases.md
> Move 0.4.7 to old releases, update links to 0.5.0 final

- blog/_posts/2015-10-23-auto-diff-in-julia.md
- downloads/index.md
- downloads/oldreleases.md
- downloads/platform.md
macOS (10.12) is released today.
This pull request replaces Mac OS X, OS X, OSX, etc. with macOS to be consistent with the new OS.
> Replace references to Mac OS X with macOS

- css/screen.css
- index.md
With this change the `page-width` is properly `100%`
> Make benchmark table not spillover on home page

- blog/_posts/2016-10-03-StructuredQueries.md
This PR adds my blog post describing my work on the jplyr.jl/StructureQueries.jl package this summer. It is admittedly a bit long; I hoped to include enough information to give helpful context to anybody (including my future self) who wants to contribute to the project. I'm happy to break it up into a series of blog posts, if that'd be more appropriate.
TO-DO:
> RFC: Add StructuredQueries.jl summer project blog post

- community/index.md
JuliaDiffEq hosts DifferentialEquations.jl, ODE.jl, and Sundials.jl. A small descriptor line was included like the others.
> Add JuliaDiffEq

- community/index.md
Particularly since now julia-vim, julia-emac etc have all been moved out of JuliaLang.
Arguably this should be at the top,
since everyone who uses julia must be using an editor.
I put it at the bottom, though, because who am I to say what is more or less important?
cf: #383
> Link to JuliaEditorSupport

- publications/_EDIT_ME_index.md
- publications/julia.bib
Hi!
I have recently published and presented a new paper about Julia's support for hybrid computing.
The venue was SPLASH (in particular, SEPS workshop) that was held in Amsterdam Oct 30-Nov 4.
Corresponding BiBTeX has been updated.
Kind regards,
Peter
> added a SEPS 2016  publication (Amsterdam, part of SPLASH)

- learning/index.md
Someone turned up on the Gitter today confused 
because there were references to things that no longer existed in the 2014 videos.
They assumed since they were at the top, that these were the videos to start with
> Put 2015 video above 2014 videos

- soc/ideas-page.md
Added parallel LightGraphs to proposed GSoC themes.
> Update ideas-page.md to include LightGraphs parallelism effort

- soc/ideas-page.md
GGPlots.jl adds a grammar of graphics API to Plots.jl. @tbreloff already has some starter code though there's still more to do, making it an easy project to get started with. But given chats with people throughout the ecosystem, many people are holdouts on Plots.jl until it has this style of API (I guess a lot of data scientists really like it?) so it would be a very big gain for Jullia.
> Add GGPlots.jl project

- soc/ideas-page.md
New version of https://github.com/JuliaLang/julialang.github.com/pull/468 since that PR seems to have been borked.
This creates a new theme around numerical linear algebra, moves the related projects there, and adds a new one based on Native Usage of LinearMaps in Iterative Solvers 
>While one normally thinks of solving the linear equation Ax=b with A being a matrix, this concept is more generally applied to A being a linear map. In many domains of science, this idea of directly using a linear map instead of a matrix allows for one to solve the equation in a more efficient manner. Iterative methods for linear solving only require the ability compute A*x in order solve the system, and thus these methods can be extended to use more general linear maps. By restructuring IterativeSolvers.jl …
> Update linear algebra projects

- downloads/index.md
The proposal for this textual change come from this thread:
https://discourse.julialang.org/t/gurobi-jl-precompile-fails-after-upgrade/990
among many other where users have had issues using packages on nightlies, thinking that it's advisable or supported like that in some way. Thus I am making this wording stronger, even mentioning "You can expect many packages not to work with this version" since generally that is the case, and maybe that will help more users declare upfront that the problem is due to using the nightly builds.
It's still a little redundant so maybe it can be workshoped more.
> Update nightly text

- soc/ideas-page.md
This PR breaks up the giant " Scalability of technical computing for big data applications" into smaller and more mangagable themes. That main theme is still there for holding projects which did not fit in other places (and it makes sense: what's there is now SIMD, threading, and parallelism). 
Numerical optimization was pulled out to its own theme. I also made a theme which I called "Base Mathematics Libraries" for:
- Upgrading openlibm
- Special functions
- Matrix functions
- Fast bignums in Julia
- Random number generation
Maybe there could be a better name for this theme?
Also, the data related projects were moved to a theme "Data Handling".
Together, I think this makes it easier to navigate. Note that this is branched off of https://github.com/JuliaLang/julialang.github.com/pull/467, …
> Group GSoC Projects by themes

- community/index.md
Implements #444 and #445. It adds the orgs of #445 and then subdivides as suggested in #444, using a consensus between the different methods mentioned in the thread. While you can always argue some changes in "what goes where", I think most of the categorizations here are well accepted enough to make this easier to read.
> Add orgs and subdivide

- downloads/plotting.md
I think it's about time we added Plots.jl to the downloads page. I tried to keep simple while mentioning Plots' two main features: backend-independence and recipes. The code example highlights the first (and ease of use), while a link to the ecosystem page highlights the extension functionality.
> add Plots to downloads page

- soc/ideas-page.md
I just received a personal email from someone applying for the complex numbers in convex.jl project which was completed last summer. It's obviously misleading to leave these projects listed on julialang.org. Anyone who would like to propose new optimization projects is more than welcome to list a new one, of course.
CC @madeleineudell @pkofod
> remove outdated optimization projects from GSOC list

- soc/ideas-page.md
This adds a new project to the differential equations section which is to build a library of differentiation tools for native differential equation solvers. This is a very self-contained project which should take about a month or 2 depending on experience, but would expose the student to all sorts of Julia libraries like ForwardDiff/ReverseDiff, Calculus, and SymEngine, with the final project being a major win for JuliaDiffEq (and some components may be useful in other places in scientific computing). I don't think that getting started on this is very hard, and so I think this is the best GSoC project for JuliaDiffEq. Because of that, I put it on the top of the JuliaDiffEq part. [More details are laid out here.](https://github.com/JuliaDiffEq/DiffEqDiffTools.jl/issues/1)
To not take up …
> DiffEqDiffTools project

- _config.yml
- _includes/links.html
- _layouts/common.html
Was just going to edit the gsoc page quickly and fell down a rabit hole. Anyway, this adds an "edit on github" link at the bottom of pages to make that a bit quicker / more accessible.
Also fixes a couple of urls to use relative references. This makes it easier to test a fork like [this](https://mikeinnes.github.io/julialang.github.com/); all the links and CSS don't break.
> Edit on Github link

- blog/_posts/2017-01-21-moredots.md
This attempts to fix the rendering problems by replacing a colon with a dash. Judging from previous posts (e.g. http://julialang.org/blog/2015/10/datastreams), we should also have been to get the colon to render by placing the title in quotes.
> Remove colon from More Dots blog post title

- css/screen.css
For `rtl` languages, overrides site direction in code blocks.
> Update screen.css, Make <pre> tag direction ltr

- community/index.md
Fixes link to user support in Github section by updating to Usage category on Julia Discourse.
> Update link to user discussion forum.

- soc/projects/diffeq.md
Given discussions in emails, I think it's wise to extend the parts on PDEs a little bit. I extended the "Discretizations of partial differential equations" project to give more details on what will be done, and directions the students can go. It's still a very open project, but this gives some very concrete directions.
Secondly, I added a project for wrapping Fenics. This was discussed on the discourse as probably the best short-term course of action for getting Julia a finite element toolbox. It would be at the level of a GSoC student since it can mostly be done with PyCall and, since it's just a wrapper, intimate knowledge of finite element methods won't be needed (and students will probably learn a lot in the process!). 
I also added to the Bayesian section a mention of Klara.jl.
> More Details in PDE Projects for GSoC

- downloads/index.md
- downloads/plotting.md
We've been working on JuliaPro for a while, and it is now quite robust and easy to use and install. Adding it here as an option for others to have an alternative way.
> Add JuliaPro as a way to download Julia.

- soc/projects/general.md
I am sorry to say, but I just today discovered I am listed as a SoC Mentor which I new nothing about. While I am always happy to help out at Projects I am involved in, I do not think I can promise the time to take on the responsibilities of being an official Mentor. I don't think a promise like this should be made so lightly.
There must have been an internal miscommunication along the line, because both "JuliaML" project ideas listed here are news to me. I am unsure what a SoC-length "LearnBase" project could even entail at this point, so maybe it is better to just remove the idea. I think to remember @tbreloff writing some text like this last year, so maybe it is some leftover text from the past?
I am sorry for this mixup. I am sure the intentions were good. I just don't want to make …
> Remove LearnBase from SoC

- downloads/index.md
- downloads/platform.md
The macOS binaries don't work correctly on 10.7, see https://github.com/JuliaLang/julia/issues/20651 (which doesn't seem to be about to be fixed any time soon an most likely won't be fixed at all).
Although the binary would still have 10.7+ in the name, at least with this change the information on the website would be correct (I had a puzzled coworker wondering why `Pkg.add` was failing).
> Update minimum requirement info for macOS to 10.8 in download pages

- community/index.md
We've founded "EcoJulia", an organisation for Ecology in Julia. We're currently two members, Tim Poisot and myself, both university professors in Ecology who use Julia professionally, but we aim to expand. Our first Julia package (SpatialEcology.jl) has just been submitted to METADATA.
https://github.com/EcoJulia
> Add the EcoJulia organization

- blog/_posts/2017-06-27-julia-0.6-release.md
Quite brief. We should also do a 0.6 highlights post as was done for 0.5, though we should get 0.6 release on JuliaBox with 0.6-specific syntax recognized in Jupyter first. That will make things look a little more polished.
> Add a brief 0.6 release announcement blog post

- downloads/index.md
- downloads/platform.md
Fixes #525 
Also see https://discourse.julialang.org/t/getting-julia-running-on-atom/3932/5
I hope this is sufficiently clear, and that I've chosen the correct recommended installation steps. I'm happy to revise as needed. 
In addition, I've added direct "help" links from the downloads page for each of the major platform releases and release candidates.
> Add generic linux binary install instructions

- downloads/index.md
We can add it back once the buildbot is back online, but as of now it's been offline for several months, so there's nothing to download for PPC at the moment.
> Remove link to PPC nightly binaries

- downloads/index.md
The PowerPC link for 0.6 release binaries was actually RC3, since the PPC buildbot went down before the release binaries were built.
> Remove outdated link to 0.6 prerelease PPC binaries

- index.md
Keep commented for next year's use.
> Remove JuliaCon and GSoC mentions.

- blog/_posts/2017-08-09-dsl.md
Escaping the code prevents the hygiene mechanism from introducing doing its work, thereby letting you capture variables from the call site – no?
> Hygienic -> unhygienic

- community/index.md
For some reason, the title format was changed in 829638f04715b0e9cf5833cb2752f02dc08d3cc2, which makes the top of the community website look like – layout: default title: Julia Community —
> Fix title formatting

- index.md
It seems as though the url for JuliaBox has changed from an org to com tld. The current https://juliabox.org url gives a not found error.
> Fix dead link for JuliaBox

- community/index.md
The Git diff is really confusing; I recommend just looking at the rendered page.
This cleans up the community page by making our official channels more explicit and by removing a lot of package-specific information.
If you're wondering why I chose `##` and `###` markdown header levels, clone and build this branch then look at the rendered page; IMO it looks much, much nicer this way, otherwise the headers are enormous.
> Clean up the community page

- community/index.md
Some extra info on how to get support for Julia was added to the Julia repo as part of https://github.com/JuliaLang/julia/pull/24052, but we decided that it would be more appropriate to put it here. I've therefore filled out the Community page slightly with content from that PR. The page now has more description of what you might use each channel for. It also highlights that newcomers are welcome on Discourse.
> Add extra info on Julia support to the community page

- soc/projects/diffeq.md
- soc/projects/hpc.md
- soc/projects/images.md
- soc/projects/ml.md
- soc/projects/numerics.md
- soc/projects/tooling.md
Get rid of completed GSoC projects to clear up space and make it easier to find what's available. 
@timholy do you agree with taking image segmentation off?
@MikeInnes are there any of the Flux.jl projects to remove?
> Prune GSoC

- downloads/index.md
Bypasses `status.julialang.org`, and prepares for the new nightlies naming convention
> New nightlies naming convention

- downloads/index.md
- downloads/oldreleases.md
As part of the process of normalizing the structure of the URLs on AWS, we're renaming `osx` to `mac` everywhere, and replacing `osx10.x+` in the file names to `mac64`. **All links to the old URLs will still work; the files in the `mac` tree are copies of those in the `osx` tree, which still exists.**
Note that with this new naming scheme, OS X 10.6 and 10.7+ are no longer distinguishable in a consistent manner. Because of that, and because both OS X 10.6 and Julia 0.2 are _way_ past EOL, the link for Julia 0.2 on OS X 10.6 has been removed. The new link points to the download for 10.7+.
This PR also moves the downloads for Julia 0.1 from Google Drive to AWS.
> Move all macOS download URLs to new location

- _includes/benchmarks.html
Corrected Python version to 3.5.4 in benchmark table, as noted in [PR 662]
(https://github.com/JuliaLang/julialang.github.com/pull/662).
Doing all the benchmark processing in the same Unix environment (same PATH) will avoid this error in the future.
> Fix Python version # in benchmark table

- _config.yml
- ecosystems/index.md
This brings back the core of the content from https://github.com/JuliaLang/julialang.github.com/blob/23114cbcce56c57b6ba0536ca15a200d9dce9444/community/index.md
but reorganises it significantly,
In particular it is only by organisation (ecosystem if you will),
not by communication medium.
So I brought all the various chat links etc up inline.
Also I deleted a lot of stuff, like lists of particular packages.
It is now just about the various sub-ecosystems
> Add Ecosystems Page

- ecosystems/index.md
Rference:
* https://discourse.julialang.org/t/http-juliastats-org-domain-seems-to-have-expired/7192
> Rename JuliaStats URL

- community/index.md
I add a manual link to translate in Korean.
This link is working on https://github.com/juliakorea/translate-doc
> add korea manual URL

- css/screen.css
Not a drastic change, but makes various small things more readable. The previous wide column format really felt like a huge wall of text. Also adds quote formatting, inline code formatting, and a `desc` class for inline image captions.
> Blog Formatting

- _publications/BDFP2014.md
- _publications/BFD2017.md
- _publications/BVD2016.md
Also, I couldn't get the Docker instructions to work, the container doesn't ship `gcc` but the RedCloth dependency of Jekyll needs it to build a native gem. Worked fine locally, using `bundler`.
> Add some publications.

- learning/index.md
Added new resource in PR #691, but then that cheatsheet got rolled into JuliaDocs, so this updates URL
> correct fasttrack url, update to pr #691

- blog/_posts/2017-12-25-ml&pl-zh_tw.md
The [page](https://julialang.org/blog/2017/12/ml&pl-zh_tw) did not seem to be in the correct format. I found that it might be owing to missing a `</a>`
> add missing `</a>` to Zh_tw-ml&pl 

- downloads/index.md
- downloads/oldreleases.md
Given the current pace of development of 0.7, the incompatibilities between 0.7 and 0.5, and the fact that we're very close to 1.0 (at which point _all_ pre-1.0 releases will be unmaintained), 0.5 is now unmaintained. This PR marks it as such. I'll also announce it on Discourse, and modify PackageEvaluator and pkg.julialang.org.
> Mark v0.5 as unmaintained

- community/index.md
Because the old one (julialang.cn) can not access in China, even bypassed the GFW.
I apply for considering julialang.org.cn as a new Official Julia Chinese Community site, as alternative at least.
> Another Julia Chinese Community.

- ecosystems/index.md
I added a link to https://github.com/JuliaLangGerman
At the momen I write a german manual for Julia https://github.com/JuliaLangGerman/Julia_Handbuch_Deutsch that I link , too.
> added a link for german documentation

- soc/guidelines/index.md
We should encourage the use of Discourse for questions, since it's easier for students who have the same questions to avoid having to ask multiple times. Also the Slack channel for GSoC is #jsoc, not #gsoc.
> Point to Discourse, correct Slack info

- downloads/index.md
Currently on the downloads page but I can put it wherever.
The thing about this is that clicking the button does not and cannot star the project; that would require entering GitHub credentials and a call to the API, which is pretty sketchy. Instead it directs you to the GitHub page, where hopefully the person who clicks star on our page will be logged in and willing to click it on GitHub.
This is what it looks like:
> Add a GitHub star button

- _layouts/common.html
The current color scheme is nice and unobtrusive, but it makes the button look like it's greyed-out and disabled.  This keeps it neutral but adds a color similar to the links on the page to make it clear that it can be clicked on.  Some discussion here: https://github.com/JuliaLang/julialang.github.com/issues/683
> Make the "Donate Now" button not look disabled

- index.md
These were moved into their own repository, so the current links are broken.
> Update links to microbenchmarks

- soc/projects/tooling.md
I also moved the WebIO.jl project to the GUI category, since it doesn't really seem to fit into the IDE category.
@shashi Would you like to co-mentor this, given the link with Observables?
> Add GUI category and QML project

- _publications/PKMANR18.md
We have submitted a JOSS article on Optim.jl that has just been published, and hope you can add it to the list of publications on julialang.
Should the title have brackets around Julia as in BiBTeX?
Ref @pkofod
> Add Optim.jl JOSS article

- downloads/index.md
- downloads/platform.md
See https://github.com/JuliaLang/julia/issues/26459#issuecomment-373117374
> Mention Windows Management Framework requirement.

- ecosystems/index.md
These typos have been bugging me for while
Also while I was here I made  some of the internationalization resource uses similar descriptions because they have similar content.
> Improve consistancy and fix typos

- community/index.md
The current link (julia.meetup.com) misses many groups, and includes many non-Julia groups.
> Add links to meetup groups

- blog/_posts/2018-06-19-missing.md
Added in https://github.com/JuliaLang/julialang.github.com/pull/770.
> Fix footnotes syntax in missing values blog post

- blog/_posts/2018-06-19-missing.md
Also update output when showing array, and drop backticks in headings since they currently give a really weird result (small font).
@ViralBShah Maybe there's a way to fix the font of code in backticks in headings? They currently look like this:
> Enable Julia syntax highlighting in missing values post

- .htaccess
- utf8proc/doc/index.html
- utf8proc/index.html
- utf8proc/releases/index.html
This adds a redirect for julialang.org/utf8proc (fixes #809) using an [htaccess file](https://mediatemple.net/community/products/grid/204643080/how-do-i-redirect-my-site-using-a-htaccess-file).
I have no idea how the julialang web server is configured.  Does it support `.htaccess` redirects like this?  @ararslan, do you know?
> add redirect for utf8proc site
