JuliaLang/julialang.github.com

- downloads/index.md
@ViralBShah suggested adding some Juno download links to the Julia downloads page, so I've tried to do that in a sane way. Suggestions are very welcome.
Incidentally, this page could probably be earmarked for a rewrite, a lot of it is crufty or even out of date.
> Juno download links

- community/index.md
> Add new mexican meetup group for Julia.

- downloads/index.md
Waiting for binaries to actually be uploaded
> Update download links for v0.3.5

- teaching/index.md
- moved Brown University up for alphabetical order
- added a course taught at the University at Buffalo. IE 572 Linear Programming.
> add a course taught at the University at Buffalo

- gsoc/2015/index.md
As requested, here is an outline of a GSoC project for improving Julia Bignums.
> Add a Julia Bignum GSOC project

- blog/_posts/2013-04-05-distributed-numerical-optimization.md
Haven't previewed this, hopefully looks okay.
Ref #204
> add licence to blog post

- publications/julia.bib
I wasn't able to run pandoc to regenerate the markdown files:
```
$ make
...
pandoc-citeproc: error while parsing the XML string
pandoc: Error running filter pandoc-citeproc
```
> update bibtex entry for JuMP paper

- learning/index.md
Added bullet points to videos. Reduced videos in size
> Add Introducing Julia wikibook; formatting

- learning/index.md
Leah Hanson's video on How Julia Goes Faster in Topical Material.
Also added a link to my [David Sanders] homepage. 
Note that I am not sure that there should be links to peoples' homepages, but we should be consistent...
> Added 3 tutorials (tutorial section) and a video

- community/index.md
[JuliaDSP](https://github.com/JuliaDSP) is an informal organization focusing on packages for digital signal processing in Julia.
> Added JuliaDSP to the list of organizations

- community/index.md
We made JuliaTokyo official website!
cc/ @sorami
> Modify Julia Tokyo URL

- learning/index.md
And the supported material for Andreas' talk.
> added talk by Jiahao

- _includes/links.html
Add a prominent, temporary JuliaCon banner to the main page. I think given we are 1.5 months out, this makes sense to really advertise. This is what it looks like:
> JuliaCon banner

- _includes/links.html
- blog/_posts/2015-05-23-jsoc-cfp.md
As requested by @ViralBShah.
Should we set up an email group (a la juliacon) to manage inquiries and submissions?
> RFC: draft of jsoc announcement

- community/index.md
* Added julia-news
* Changed URLs to a slightly shorter, nicer form
* Changed from paragraphs to an unordered list
* DRY'd out some of the wording and other small tweaks
> community: Update mailing list section

- community/index.md
* Add reference to `JuliaLangEs`, which will be the central place for the Spanish speaking community.
* Fix capitalization of `Spanish`.
* Update link to gitter chat `julialang-es` from `Ismael-VC` to `JuliaLangEs`.
> Update information for the Spanish speaking community.

- community/index.md
* Add reference to Facebook group.
* Update naming scheme of the social networks.
* Add reference to Twitter hashtag.
> Update information on for the Spanish speaking community.

- index.md
- jsoc.md
> Add information about JSoC

- community/index.md
* https://gitter.im/JuliaLang/julia
* https://gitter.im/kshyatt/julia-coverage
> Add reference to julia and julia-coverage chat rooms.

- downloads/index.md
cc @staticfloat, I sorted out the buildbots and they're working on these now, once they're uploaded to julianightlies can you move over to the julialang bucket and merge? Thanks.
> Update download links for v0.3.11

- learning/index.md
_Learn Julia_ is now in Early Access, and as such, I have included it in the list of learning resources.
> Includes references to Learn Julia

- downloads/index.md
@nalimilan I accept your reasoning.  How does this look?
> Tweak GPG and tarball support

- css/screen.css
Fixes https://github.com/JuliaLang/julia/issues/13091
> Remove `display: block` designator for links

- _includes/links.html
> add JuliaCon India info to front page

- learning/index.md
- Mastering Julia book
- Link to JuliaCon 2015 videos
- Two tutorials by David Sanders
> Add book and tutorials

- blog/_posts/2015-09-29-compose3d-threejs.md
This PR adds my blogpost on Compose3D and ThreeJS. Please let me know if there any changes to be made.
Also currently I've linked the images and gifs to the gist I uploaded. Should I add them to the julialang repo and link it from there?
cc: @shashi  @SimonDanisch @ViralBShah
> Compose3D JSOC blog post.

- blog/_posts/2015-10-22-glvisualize.md
Hi all,
hope this is good as it is. Sorry for eventual errors, it got pretty late :( Feel free to make corrective changes!
Thanks for making JSoC possible!
@Keno, @shashi, @jiahao, @ViralBShah 
Best,
Simon
> GLVisualize JSoC post

- blog/_posts/2015-09-27-auto-diff-in-julia.md
@mlubin @ViralBShah This PR adds my JSoC blog post about ForwardDiff.jl. Let me know if the formatting (or anything else) requires updating.
> JSoC blog post about ForwardDiff.jl

- community/index.md
qq gourps is a kind of thing like chat room in China,more convenient if there is one in China
add QQ groups to the community
add USTC(university of Science and Technology of China) Julia User Group,QQ group:316628299 in QQ groups
> add qq groups to community

- jsoc.md
update descriptions about qq services and add some other qq groups to the community hope this would help :-)
> update qq groups in community

- community/index.md
correct the word develop and change the form of QQ info
> revise the form of qq groups info

- community/index.md
Julia programming groups have both academic and industry users. Our website is at http://julia.org.cn/
> Add a QQ group from China

- community/index.md
julia.org.cn is a QA community for Chinese Julia users
> Add Julia China website (julia.org.cn) to commmunity

- downloads/index.md
> Update release links from 0.4.1 to 0.4.2

- downloads/index.md
If anyone has a chance to test these out quickly before we do a proper release, it'd be much appreciated.
> Add Juno v0.4 downloads

- downloads/index.md
> Update download links from 0.4.2 to 0.4.3

- blog/feed.xml
- css/screen.css
tiny bit wider main layout, stops the menu breaking
wider blogindex stops the post names breaking,
removed nil layout to stop jekyll complaining
> small layout tweaks

- community/index.md
We have our first meetup scheduled for Feb 18. Gadfly author Daniel Jones speaking. Join us if you are in the area!
> Add Seattle Julia Users to community page

- blog/_posts/2016-02-01-iteration.md
I enjoyed @timholy post , 
I prefer it highlighted.  (only drawback is the style of some unicode that are red-ish
You should be able to [view the diff without whitespace changes](https://github.com/JuliaLang/julialang.github.com/pull/327/files?w=1) by appending `?w=1`
> Highlight code in `iteration` blog post.

- _config.yml
- _includes/links.html
- css/screen.css
- index.md
Used Crimson Text font and a size scale for headers.
The navbar now shows where you are guiding you around better. Harmless easing animation on hover.
> better typography and navbar

- soc/ideas-page.md
Includes link to ParallelAccelerator
> Update description of multithreaded kernels

- soc/ideas-page.md
> Add constrained optimization, tweak CUTEst description

- teaching/index.md
computational economics course with julia.
> added sciences po paris dept of economics 

- soc/ideas-page.md
Copied from https://github.com/numfocus/gsoc/blob/master/2016/ideas-list-juliaopt.md
CC @madeleineudell
> convex.jl project idea

- soc/ideas-page.md
As suggested by @shashi I've copied these over from the Juno page, hopefully to an appropriate place.
> Add Juno projects

- soc/ideas-page.md
As discussed in https://github.com/JuliaLang/julialang.github.com/issues/339#issuecomment-185408977
@ViralBShah, please merge if you're OK with this.
> Delete GPU computing project

- _includes/links.html
- index.md
> Add banner for JuliaCon 2016

- soc/ideas-page.md
> Updated GSOC ODE.jl

- blog/index.html
There have been very interesting posts there recently.
> Add mention of the Julia Computing blog on the Blog page

- blog/_posts/2016-03-01-parallelaccelerator.md
This fixes the formatting stuff that was broken in #351. It now Jekylls correctly, unlike the previous version, which was "GitHub Flavored Markdown" (sorry!).  @ViralBShah @johnmyleswhite, can one of you merge this?
> Corrected image URLs and code block formatting.

- soc/ideas-page.md
Add QML bindings for Julia. Should I add my email address here as possible mentor?
> Update ideas-page.md, add QML bindings

- soc/ideas-page.md
Also make hyperlinks out of other links.
> QML idea update with link to QML.jl

- blog/_posts/2016-03-01-parallelaccelerator.md
This tweaks a few things in the ParallelAccelerator blog post,
including a change suggested in #353.
> Minor typo fixes and clarifications.

- learning/index.md
> adding a new upcoming book in the Learning page

- community/index.md
Added Julia Korea user group to the community list.
> Add Julia Korea community

- learning/index.md
> Add "Julia High Performance" to Books

- community/index.md
After Post: https://github.com/JuliaLang/julia/issues/16357#issuecomment-222144998
See Roadmap: https://github.com/JuliaMath/Roadmap.jl/issues/2
> Add Julia Math Github group

- learning/index.md
Julia Programming for Operations Research is now published in print. 
Disclaimer: I am the author.
> a book is published

- community/index.md
- community/standards/index.md
- community/standards/julia_stewards.md
- community/stewards/index.md
I'm not certain whether the link I inserted will work, but one can always hope.
> Add page on Julia community stewards

- _includes/juliacon-player-2016.html
- index.md
> JuliaCon 2016 random video player

- blog/_posts/2016-08-22-GSoC2016-Graft.md
Please review: @ViralBShah @shashi
> Blogpost for GSoC2016 Graft.jl

- teaching/index.md
This is an edX MOOC that just started this month. I'm not sure if its important to mention it's a MOOC (massive online open course) or not, either way I think we should really promote this course, since it's open and even if there is a verified track that costs money, people can also learn all this for free if they wish.
> Add Optimization Methods in Business Analytics

- blog/_posts/2016-09-10-biojulia2016-mid.md
This is a midterm report of my BioJulia project this year. I wrote about new stuffs I've implemented in the last months. I wanted to wait for the release of Julia 0.5 but it would be okay since RC4 (final RC?) is now available. This should be merged after <https://github.com/JuliaLang/METADATA.jl/pull/6316>.
CC: @ViralBShah
> add BioJulia 2016 - midterm report

- learning/index.md
> Add another Julia For Data Science book

- blog/_posts/2016-09-16-juliacon2016.md
Hello, everyone. This is my proposed blog entry for JuliaCon 2016. I must make a few disclaimers here: 
* The views in this post are my personal opinions alone
* It was not possible for me to cover and comment on every talk, especially because there were parallel sessions going on. But I did my best to do justice to the talks I liked. 
I would highly appreciate any feedback or edits you might have. Thank you!
> Add JuliaCon blog post

- _layouts/common.html
Ref: https://github.com/JuliaLang/julialang.github.com/issues/187
Working demo: http://julialanges.github.io
CC: @yuyichao
> RFC: Add Transifex translation scripts.

- downloads/oldreleases.md
To be consistent with statement on downloads/index (ref #417).
> Declare 0.3 unmaintained on oldreleases page

- publications/_EDIT_ME_index.md
- publications/julia.bib
Updated with publication RSLLBHGL16. Have not run Jekyll, asking for help with that, thanks,
> Updated with publication RSLLBHGL16

- community/index.md
Rio de Janeiro meetup no longer exists.
> fix brazilian meetup

- blog/_posts/2016-10-03-StructuredQueries.md
This should fix the code block formatting issues noted after #427 was merged. @ViralBShah
> Fix formatting and typos

- blog/_posts/2016-09-21-juliacon2016.md
I wonder if "on" is the right preposition here? Also, another possibly useful title would be "Looking Back at JuliaCon 2016"
> Modify title

- downloads/index.md
Remove "32bits" since that's implied by v7.
> Update ARM nightly link and rename it to ARMv7

- learning/index.md
- Added the Julia Cookbook, along with the details of the book  (Publisher - Packt)
- I am the author of the book.
> Added Julia Cookbook

- learning/index.md
This is a very in-depth tutorial being given at a workshop tomorrow. It assumes that the reader is familiar with programming in other languages, and so it spends only a small amount of time on simple syntax, and goes straight into multiple dispatch, call overloading, etc.
> Add tutorial

- community/index.md
https://github.com/JuliaGraphics/Graphics.jl/issues/7#issuecomment-257030978
> added links to JuliaGraphics and GiovineItalia

- teaching/index.md
Update list of courses using Julia.
> 2016 courses at the ULg using Julia

- community/index.md
Julia-users moved to discourse this morngin
> Move julia-users to discourse

- soc/ideas-page.md
@sunoru 's RNG.jl project from last year was really great, but you can see there are some remaining issues. It would be nice to get another hand on it next year. Also, I think RNG.jl should be migrated to JuliaMath so that way it can start becoming a more standard part of Julia, maintained by more members of the community.
> Add to random number generator project

- soc/ideas-page.md
I created a theme for numerical methods of differential equations. These are some projects I have been leaving around JuliaDiffEq which I think are both easily accessible to newcomers, don't require too much mathematical sophistication (undergraduate mathematics or graduate non-math like CS/Engineering would suffice), but also have very tangible and useful results. 
Many of these proposals give ecosystem wide results, for example the global sensitivity analysis results using the common interface would be able to be used with OrdinaryDiffEq.jl, ODE.jl, Sundials.jl, DASKR.jl, DASSL.jl, and I can keep listing. So these would have a very large affect on the ecosystem as a whole.
> Theme: Numerical Methods for Differential Equations

- soc/ideas-page.md
- soc/projects/diffeq.md
This has it as a diffeq page. Or should it be a scientific applications page which includes optimization and machine learning projects?
> Add DiffEq

- css/screen.css
Having explicit text-align prevent rtl sites to have appropriate text-align:  
to check : http://julialanges.github.io/ and select Persian
ref: http://www.w3schools.com/cssref/pr_text_text-align.asp
@Ismael-VC
> Update screen.css, remove explicit text-align for site

- community/index.md
ref https://groups.google.com/forum/#!topic/julia-opt/jU2KK2xPtHo
> Move julia-opt to "Old google groups"

- publications/index.md
I assume this is an artifact of the process used to create this page, but I don't know how to fix that. Feel free to close this PR in favor of one that fixes the root cause, but I figured this was a simple enough edit.
> Remove duplicate entry; extra tags

- learning/index.md
- Added the video course by Packt. 
- I am the author [produced from my published work (https://www.packtpub.com/application-development/julia-cookbook/)]
- Released on Jan 31st, 2017
> Added my video course

- soc/projects/graphics.md
The QML bindings description was still from last year. In the mean time, I feel my QML.jl package is mature enough to be proposed as a topic. I'd be willing to mentor if needed.
> Update QML description

- soc/projects/numerics.md
I added a bunch  of recommended skills and expected results for the numerics page. In general, those should be about all that's needed for the projects. I tried to really emphasize the difference of "for this, you just need to know calculus/linear algebra well, and be familiar enough with this other thing to pick it up as you go long" vs "you might need to know some (insert non-calculus/linear algebra) to do this well"
> Add recommended skills and expected results

- soc/projects/numerics.md
ping @jiahao @simonbyrne @andreasnoack @jaredcrean2
> add mentors to Numerics projects

- soc/projects/numerics.md
I and Luis Benet (@lbenet) are possible mentors.
> Add GSoC projects on interval arithmetic

- soc/ideas-page.md
- soc/projects/hpc.md
- soc/projects/images.md
- soc/projects/numerics.md
This adds new projects for improvements in visualization, bindings for OpenCV, and enhancements to image segmentation. I've flagged some potential mentors but not yet gotten permission from any of them, so here goes: @SimonDanisch, @rsrock, @maxruby, @mronian. Of course I'd be thrilled if anyone else stepped forward (this list is not meant to be exclusive).
> GSoC: remove outdated project and add new JuliaImages projects

- soc/projects/general.md
> Remove @tbreloff from mentors

- blog/_posts/2017-03-14-cudanative.md
Changed the commit hash without changing the line number.
> CUDAnative blogpost: fix line number

- blog/_posts/2016-02-01-iteration.md
Removing a slash fixes 404 link for my browser.
> Broken link

- blog/_posts/2017-03-18-julia-fresh-paper.md
A blog post for our SIAM Review paper.
> Blog post announcing our Julia paper

- soc/ideas-page.md
- soc/projects/general.md
- soc/projects/ml.md
> Add Machine Learning projects

- community/index.md
Added juliadelhi's meetup information on line 245.
> Added JuliaDelhi

- downloads/index.md
@viralbshah why did you need to wait for me to change 4 characters?
> change arm and power links back to 0.5.0

- publications/_EDIT_ME_index.md
- publications/julia.bib
New publication. Have not run jekyll, would like help with that. Thanks!
> Add ESBWGK17 Publications

- css/screen.css
- larger default width, to allow language names like "Portuguese (Brazil)" to show up without cropping
- add a maximum height and an automatic scrollbar when overflow occurs
> Adjust CSS to improve Transifex dropdown

- learning/index.md
This is a video course for developers new to Julia, who want to learn the language published by Pack Publishing.
> Update index with Learning Julia video course

- _layouts/common.html
@ViralBShah They also said they'd like a shoutout over Twitter.
> Thank fastly

- .gitignore
- Makefile
- README.md
This is a lot easier than dealing with `bundler` and `ruby` and whatnot.
> Add `make run` target to build and run inside of Docker

- teaching/index.md
Add Statistical Computing course at UCLA (biostat m280/biomath m280/stat m280, spring 2017)
> add ucla course

- downloads/index.md
- downloads/oldreleases.md
> Move downloads links to fastly-cached links

- downloads/index.md
- downloads/oldreleases.md
> update download links for 0.6.0-rc2

- downloads/index.md
I'm not sure what is the expected format so I use the base ISA name so that it's not simply repeating the same information in the parenthesis....
> Include link to aarch64 nightly binary

- _publications/HSBC17.md
@simonbyrne I created the YAML file as you suggested, could you please review and merge?
Thank you.
> Add reference for ImageQuilting.jl

- _publications/RN17.md
- _publications/RN217.md
Adds the two publications for diffeq.
@ViralBShah this is the journal that I mentioned we should get Julia software publishing: http://openresearchsoftware.metajnl.com/articles/10.5334/jors.151/
Another interesting thing about that journal is that it publishes articles for issues in research software. It might be interesting to do a piece on sustainable software development in Julia.
> add 2 differentialequations publications

- community/index.md
Updated to https://www.meetup.com/Sydney-Julia-Julialang-Meetup/
> Updated the link to the new Sydney Julia user group meetup page

- downloads/platform.md
- updates instruction for installing Julia on MacOS
> install julia with brew on MacOS

- _publications/BOMHFV15.md
Adds an article to the list of publications citing Julia.
I followed the manual steps of https://github.com/JuliaLang/julialang.github.com/blob/master/README.md and the site built and ran fine locally.
> Add BOMHFV15 publication making use of and citing Julia

- blog/_posts/2017-06-25-dsl.md
Based on a question from the JuliaCon 2017 hackathon, I wrote a blog post explaining (my understanding of) how to use macros to create Julia objects.
Please check that what I'm saying is actually correct!
> Add blog post by David P. Sanders on making a DSL

- soc/projects/diffeq.md
Getting ready for the next year, I am sectioning off some projects which would do well as GSoC projects. Some projects are deleted since they aren't as relevant anymore, and projects which are covered by this years GSoC project are also removed. New projects were added.
This of course doesn't need to be merged anytime soon and may change before the next GSoC cycle, but I wanted to get these ideas jotted down.
> Updated DiffEq GSoC Projects

- learning/index.md
Neither of the referenced books is expected to be published.
> Remote outdated references

- blog/_posts/2017-09-06-gsoc-derivative_operators.md
Sorry I didn't catch these before!
> Fix two errors in derivative operators post

- community/index.md
> Add Barcelona and Singapore meetup groups

- teaching/index.md
hi, I just added info on the classes (Distributed Systems) I give at Federal University of Alagoas (Brazil).
> adding UFAL classes on distributed systems

- _publications/SOG16.md
I have updated the reference after the article appeared on the journal.
> Updated reference to the publication about SwitchTimeOpt.jl package

- downloads/plotting.md
Hi,
I noticed some broken links while reading the documentation.
I believe the ones you meant are now at these addresses.
Best regards,
Matthias
> Fix broken links to Plots.jl docs in plotting.md

- index.md
> Update front page JuliaCon reference to 2017

- soc/projects/diffeq.md
- soc/projects/hpc.md
- soc/projects/images.md
- soc/projects/ml.md
- soc/projects/numerics.md
- soc/projects/tooling.md
This project was put as a potential project during the last GSoC, and while this never happened we really liked the idea.
> Add MD GSoC Project

- downloads/index.md
I bless the rains down in Africa
> Update 0.6 download links to 0.6.1

- _publications/DTP16.md
The described publication uses Julia to create a two-step linear programming model for energy-efficient timetables in metro railway networks.
> A two-step linear programming model for energy-efficient railway timetables 

- blog/_posts/2013-03-30-julia-tutorial-MIT.md
A problem occurs when loading tutorial page's youtube videos. Mixed content can't be loaded when using HTTPS
> Update youtube iframe src (videos can't be watched)

- ecosystems/index.md
Fix
https://github.com/JuliaLang/julialang.github.com/pull/664#issuecomment-343879537
idk how that happened.
> Make Ecosystems page UTF8

- _publications/JFC17.md
We used Julia + JuMP for flux balance analysis simulations of metabolic networks.
> Create JFC17.md (Julia + JuMP for metabolism optimization)

- downloads/plotting.md
sin() and cos() changed to sin.() and cos.()
linestyle is now a symbol
> Update PyPlot example

- learning/index.md
This is a new book authored by @anshuljoshi and @rahulkp220 published by Packt Publishing.
Its available on [Amazon](https://www.amazon.in/Learning-Julia-Anshul-Joshi-ebook/dp/B01MYRGB3O)
> Added Learning Julia

- learning/index.md
Re: https://discourse.julialang.org/t/excellent-cheat-sheet/7792
> Add fast track to julia to resources

- blog/_posts/2017-12-25-ml&pl-zh_tw.md
As he [commented](https://github.com/JuliaLang/julialang.github.com/pull/689#issuecomment-352428033) in #689 
@iblis17
> Add Traditional Chinese translation of ml&pl blog post

- ecosystems/index.md
Add link to JuliaAstro homepage and Gitter rooms, add JuliaPhysics organization.
> Add links to ecosystems page

- downloads/oldreleases.md
Sorry folks, I hadn't intended a sequel, but I missed this the first time around.
> Mark v0.5 as unmaintained (unexpected part 2)

- soc/projects/diffeq.md
- soc/projects/ml.md
I am updating the DiffEq-related GSoC projects since we're starting to get questions.
> Update GSoC projects

- _layouts/common.html
@Kungfooman pointed out the numfocus link is old
> fixed numfocus link

- soc/ideas-page.md
- soc/projects/ml.md
Thoughts?
I have removed the dataset packaging project, because after nothing came out of it the last (few?) GSOCs,
I went and completed it myself.
This project extends that.
See the Files Changed for the project desc.
> GSOC: OAI-PMH project

- downloads/index.md
- downloads/nightlies.md
> Move nightlies to their own page

- learning/index.md
> Add links to online tutorials

- teaching/index.md
> Added course in Dortmund.

- learning/index.md
for three upcoming tutorials in the coming months :)
> Add online tutorial information

- learning/index.md
Just realized I forgot to update the youtube link for the rescheduled event! Sorry about that! @simonbyrne
> Fix broken link in tutorials

- ecosystems/index.md
added the JuliaData org to the list of ecosystems in the Data category
> adding JuliaData as ecosystem

- soc/projects/ml.md
AI requires well defined definitions to be effectively develop applications. AIMA frameworks can benefit practitioners in designing their problems better. Such a framework is not offered by any other libraries today.
> Develop an AI package in Julia based on AIMA

- soc/projects/general.md
Outline two possible approaches to target this task.
Pinging @ChrisRackauckas and @amellnik for comments
> Add a GSOC project for WebAssembly

- soc/projects/ml.md
If there is further trimming required will be happy to do so.
Refer to https://github.com/JuliaLang/julialang.github.com/pull/726 for comments. 
@ChrisRackauckas, pls. review the content.
> Update ml.md to shorten the AIMA project

- soc/projects/ml.md
> Hyperlinks to repository missing.

- soc/projects/numerics.md
@andreasnoack and @jiahao: maybe you want to mentor these projects as well?
> Add and update GSOC projects for numerical maths

- soc/ideas-page.md
sorry, missed the markdown double newline...
> add newline

- soc/projects/general.md
> improve title

- blog/_posts/2018-02-21-gsoc2018-numfocus.md
Just a quick blog post that explains our GSoC participation with NumFOCUS this year.
> Blog post for NF GSoC 2018

- soc/projects/general.md
> Delete InteractNext.jl GSoC project

- ecosystems/index.md
Mostly spelling and capitalization tweaks
> Minor tweaks to ecosystems/index.md text

- index.md
Some very minor attempts at tweaking the text in two places, and capitalizing YouTube...
> Minor tweaks to text

- soc/projects/general.md
Moved some of the old ones to the bottom of the page.
> Added a couple of new GSoC projects

- soc/projects/ml.md
> Add projects on Parquet and JuliaDB on GPU

- _publications/MC16.md
> a paper from 2016

- soc/projects/tooling.md
> WebIO GSoC idea

- teaching/index.md
Updated list of lectures using Julia @ University of Cologne, Germany
> Updated list of lectures using Julia

- downloads/index.md
> Added github repo link on downloads page

- ecosystems/index.md
> Fixes typo on ecosystems page

- teaching/index.md
> Classes using Julia for teaching: link directly to edit page

- teaching/index.md
I have edited `teaching/index.md` to include classes taught at Université de Montréal.
> Edited teaching/index.md

- benchmarks/index.md
Pretty darn significant omission, no?
> Added missing link to benchmark source code

- _publications/RN18.md
Controlling randomness in biological organisms in Julia.
> add MINC publication

- _publications/H18.md
The paper came out last month. Please let me know if anything is missing.
> Add GeoStats.jl paper in JOSS

- community/stewards/index.md
> Replace reference to julia-users with Discourse

- _publications/KN18.md
> Certifying numerical estimates of spectral gaps

- downloads/index.md
- downloads/platform.md
~~**DO NOT MERGE YET.** I'm still waiting on ARMv7 binaries, then I'll purge the Fastly caches to make the links work. I'll merge this once everything is ready to go.~~ We're good.
> Update to 0.6.3

- teaching/index.md
> Added entry for University of Connecticut

- downloads/index.md
Everything is uploaded and ready, so this is good to merge.
> 0.7 alpha -> beta

- blog/_posts/2018-07-08-iterators-in-julia-0.7.md
> Add iterators blog by Eric.
